#region Copyright Notice
// This file is part of Grimace.BulkInsert.
// Bulk Insert into SQL without files
// Copyright (C) 2013 Grimace of Despair
// 
// Grimace.BulkInsert is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Grimace.BulkInsert is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Grimace.BulkInsert.FormatFile {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    [System.Xml.Serialization.XmlRootAttribute("BCPFORMAT", Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format", IsNullable=false)]
    public partial class bcpFormatType {
        
        private AnyFieldType[] rECORDField;
        
        private AnyColumnType[] rOWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FIELD", IsNullable=false)]
        public AnyFieldType[] RECORD {
            get {
                return this.rECORDField;
            }
            set {
                this.rECORDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("COLUMN", IsNullable=false)]
        public AnyColumnType[] ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharTerm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharTerm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NativePrefix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharPrefix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharPrefix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NativeFixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharFixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharFixed))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class AnyFieldType {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnyString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNVARCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARYCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARYBIN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLBINARY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LOB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharLOB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNTEXT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTEXT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLUDT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLIMAGE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VarNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNUMERIC))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDECIMAL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLUNIQUEID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARIANT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLMONEY4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLMONEY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIM8))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIM4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLFLT8))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLFLT4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLBIGINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLSMALLINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTINYINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLBIT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VarDatetime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIMEOFFSET))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIME2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTIME))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class AnyColumnType {
        
        private string sOURCEField;
        
        private string nAMEField;
        
        private AnyColumnTypeNULLABLE nULLABLEField;
        
        public AnyColumnType() {
            this.nULLABLEField = AnyColumnTypeNULLABLE.YES;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string SOURCE {
            get {
                return this.sOURCEField;
            }
            set {
                this.sOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AnyColumnTypeNULLABLE.YES)]
        public AnyColumnTypeNULLABLE NULLABLE {
            get {
                return this.nULLABLEField;
            }
            set {
                this.nULLABLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public enum AnyColumnTypeNULLABLE {
        
        /// <remarks/>
        YES,
        
        /// <remarks/>
        NO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNVARCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARYCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARYBIN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLBINARY))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class AnyString : AnyColumnType {
        
        private string lENGTHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string LENGTH {
            get {
                return this.lENGTHField;
            }
            set {
                this.lENGTHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNVARCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARYCHAR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLCHAR))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class CharString : AnyString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLNVARCHAR : CharString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLNCHAR : CharString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLVARYCHAR : CharString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLCHAR : CharString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLVARYBIN : AnyString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLBINARY : AnyString {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharLOB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNTEXT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTEXT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLUDT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLIMAGE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class LOB : AnyColumnType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNTEXT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTEXT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class CharLOB : LOB {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLNTEXT : CharLOB {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLTEXT : CharLOB {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLUDT : LOB {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLIMAGE : LOB {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLNUMERIC))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDECIMAL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class VarNumber : AnyColumnType {
        
        private string pRECISIONField;
        
        private string sCALEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string PRECISION {
            get {
                return this.pRECISIONField;
            }
            set {
                this.pRECISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string SCALE {
            get {
                return this.sCALEField;
            }
            set {
                this.sCALEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLNUMERIC : VarNumber {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDECIMAL : VarNumber {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLUNIQUEID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLVARIANT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLMONEY4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLMONEY))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIM8))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIM4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIME))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLFLT8))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLFLT4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLBIGINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLSMALLINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTINYINT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLBIT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class Fixed : AnyColumnType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLUNIQUEID : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLVARIANT : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLMONEY4 : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLMONEY : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDATE : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDATETIM8 : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDATETIM4 : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDATETIME : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLFLT8 : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLFLT4 : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLBIGINT : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLINT : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLSMALLINT : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLTINYINT : Fixed {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLBIT : Fixed {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIMEOFFSET))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLDATETIME2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLTIME))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public abstract partial class VarDatetime : AnyColumnType {
        
        private string sCALEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string SCALE {
            get {
                return this.sCALEField;
            }
            set {
                this.sCALEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDATETIMEOFFSET : VarDatetime {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLDATETIME2 : VarDatetime {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class SQLTIME : VarDatetime {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharTerm))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class CharTerm : AnyFieldType {
        
        private string tERMINATORField;
        
        private string mAX_LENGTHField;
        
        private string cOLLATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TERMINATOR {
            get {
                return this.tERMINATORField;
            }
            set {
                this.tERMINATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string MAX_LENGTH {
            get {
                return this.mAX_LENGTHField;
            }
            set {
                this.mAX_LENGTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COLLATION {
            get {
                return this.cOLLATIONField;
            }
            set {
                this.cOLLATIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class NCharTerm : CharTerm {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharPrefix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharPrefix))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class NativePrefix : AnyFieldType {
        
        private prefixLength pREFIX_LENGTHField;
        
        private string mAX_LENGTHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public prefixLength PREFIX_LENGTH {
            get {
                return this.pREFIX_LENGTHField;
            }
            set {
                this.pREFIX_LENGTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string MAX_LENGTH {
            get {
                return this.mAX_LENGTHField;
            }
            set {
                this.mAX_LENGTHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public enum prefixLength {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharPrefix))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class CharPrefix : NativePrefix {
        
        private string cOLLATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COLLATION {
            get {
                return this.cOLLATIONField;
            }
            set {
                this.cOLLATIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class NCharPrefix : CharPrefix {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharFixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharFixed))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class NativeFixed : AnyFieldType {
        
        private string lENGTHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string LENGTH {
            get {
                return this.lENGTHField;
            }
            set {
                this.lENGTHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NCharFixed))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class CharFixed : NativeFixed {
        
        private string cOLLATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COLLATION {
            get {
                return this.cOLLATIONField;
            }
            set {
                this.cOLLATIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/bulkload/format")]
    public partial class NCharFixed : CharFixed {
    }
}
